// 余额快照
export const GET_BALANCESNAPSHOT_ACTION = 'GET_BALANCESNAPSHOT_ACTION'
// 充值记录
export const GET_CHARGELOG_ACTION = 'GET_CHARGELOG_ACTION'
// 供应商
export const GET_SUPPLIER_COMPANYS = 'GET_SUPPLIER_COMPANYS'
// 供应商分析
export const GET_OUTSERVICECHARGEINFOBY_SUPPLIER = 'GET_OUTSERVICECHARGEINFOBY_SUPPLIER'
// 上游

// 按客户分析
export const GET_CUSTOMER_CHARGEINFO = 'GET_CUSTOMER_CHARGEINFO'
// 按服务分析
export const GET_OUTSERVICE_CHARGEINFO = 'GET_OUTSERVICE_CHARGEINFO'
// 按日服务分析
export const GET_ALLOUTSERVICE_CHARGEINFO = 'GET_ALLOUTSERVICE_CHARGEINFO'
export const GET_OUTSERVICE_CHARGEINFOBYDAY = 'GET_OUTSERVICE_CHARGEINFOBYDAY'

//下游按客户分析
export const GET_USAGE_NAME_SORT_BY_DOWNCHARGEDCOUNT = 'GET_USAGE_NAME_SORT_BY_DOWNCHARGEDCOUNT'
export const GET_USAGE_NAME_SORT_BY_DOWNCOST = 'GET_USAGE_NAME_SORT_BY_DOWNCOST'