// 余额快照
export const GET_BALANCESNAPSHOT_ACTION = 'GET_BALANCESNAPSHOT_ACTION'
// 充值记录
export const GET_CHARGELOG_ACTION = 'GET_CHARGELOG_ACTION'
// 供应商
export const GET_SUPPLIER_COMPANYS = 'GET_SUPPLIER_COMPANYS'
// 供应商分析
export const GET_OUTSERVICECHARGEINFOBY_SUPPLIER = 'GET_OUTSERVICECHARGEINFOBY_SUPPLIER'
