// 获取左侧菜单
export const GET_SYSTEMMENU_AJAX_LIST = 'GET_SYSTEMMENU_AJAX_LIST'
// 设置左侧激活状态菜单
export const SET_ACTIVE_MEUN = 'SET_ACTIVE_MEUN'
// 设置头部卡片
export const SET_HEADER_TABS = 'SET_HEADER_TABS'
// 设置头部卡片激活状态
export const SET_ACTIVE_HEADER_TAB = 'SET_ACTIVE_HEADER_TAB'
// 删除头部卡
export const DELETE_HEADER_TAB = 'DELETE_HEADER_TAB'
// 获取行业类型
export const GET_BUSINESS_TYPES = 'GET_BUSINESS_TYPES'
// 获取服务
export const GET_BASICS_SERVICES = 'GET_BASICS_SERVICES'
// 获取所有服务
export const GET_BASICS_ALL_SERVICES = 'GET_BASICS_ALL_SERVICES'
// 获取客户
export const GET_BASICS_CUSTOMERS = 'GET_BASICS_CUSTOMERS'
// 选择行业类型
export const CHANGE_BUSINESS_TYPES = 'CHANGE_BUSINESS_TYPES'
// 选择客户
export const CHANGE_BASICS_CUSTOMER = 'CHANGE_BASICS_CUSTOMER'
// 选择服务
export const CHANGE_BASICS_SERVICENAME = 'CHANGE_BASICS_SERVICENAME'
// 根据服务查询参数
export const QUERY_PAEAMSBY_SERVICENAME = 'QUERY_PAEAMSBY_SERVICENAME'